name: Daily Docker Image Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a la medianoche (UTC)
  workflow_dispatch:    # Permite ejecutar el workflow manualmente

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mi-imagen:latest .

      - name: Pull Trivy image
        run: docker pull aquasec/trivy:0.57.0

      - name: Run Trivy vulnerability scanner
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.cache:/root/.cache aquasec/trivy:0.57.0 image mi-imagen:latest --exit-code 1 --format table --ignore-unfixed --severity CRITICAL,HIGH

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: trivy_report.txt

      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: your-channel-name
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          message: "Daily Trivy scan completed for mi-imagen:latest"
          color: good

